## q2   

In [17]:
#Importing the libraries
#import statistics 
from statistics import mode 
import numpy as np;
import pandas as pd;
from scipy.spatial import distance
import math

from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score


#### Eucledian Distance  w.r.t  to xtrain and xtest return a single euclidean 

In [18]:
def euclidean(a,b):
    sum=0
    for count,i in enumerate(a):
        x= a[count]- b[count]
        sum= sum + x*x

    res= math.sqrt(sum)

    return res

###### Knn Algorithm
* Calculate eucledian distance of w.r.t each row in training dataset and append two list
* Created a two dimenssional list which contain label and eucledean distance
* Sort that two dimenssional array
* Took first K smallest distances from the list
* Find the maximum occurence of distance in list of K element.
* Append the label of that distance into res list.
* Return res which contain Predicted Labels 

In [19]:
def knn_classifier(x,y_train,xtest,k):
    res=[]
    for rowtest in xtest:
        c1=0
        pnt2=[i for i in rowtest]
        l=[]
        for row in x:
            
            pnt1= [i for i in row]
            twodim=[]
            dist=euclidean(pnt1,pnt2)
            twodim.append(dist)
            twodim.append(c1)
            c1=c1+1
            l.append(twodim)	
        l.sort()    #[[dist,index],[..],[..]]
        classes= set(y_train)
        d={}
        for c in classes:
            d[c]=0
        for i in range(k):
            ind= l[i][1]
            label = y_train[ind]
            d[label] = d[label]+1
        maxv=0
        for i in d:
            if(d[i]>maxv):
                maxv=d[i]
                key=i
        res.append(key)
    return res

### Major task in this dataset is to handle value "?"
1. For this purpose we used replace function which can repace character in dataset and Fillna Function which used to fill NaN valuess in dataset
2.  We use ascii value to convert catagorical data to numerical data 

In [35]:
dataset = pd.read_csv('/home/gsmodi/2SMAI/Assignment1 Dataset/Datasets/q2/train.csv')
y = dataset.iloc[:, 0].values             #dependent variables
dataset=dataset.replace('?',np.NaN)
dataset['?'].fillna(dataset['?'].mode()[0],inplace=True)
# Splitting the dataset into the Training set and Validation set

rows=len(dataset.index)
for r in range (0,rows):
    for row,col in enumerate(dataset):
        dataset.iloc[r][col]=ord(dataset.iloc[r][col])
x=dataset.iloc[:,1:22]
print(x.head())

     k    s    n    f  n.1    a    c    b    y  e.1  ...  s.1  s.2    o  o.1  \
0  107  115  103  102  110  102  119   98  112  101  ...  115  115  119  119   
1   98  115  103  102  110  102  119   98  119  101  ...  115  115  119  119   
2  115  102  103  102  110  102   99  110  110  101  ...  115  115  119  119   
3  102  102  103  102  110  102  119   98  112  116  ...  115  102  119  119   
4  120  115  110  102  110  102  119   98  104  116  ...  115  102  119  119   

     p  n.2  o.2  p.1  b.1  c.1  
0  112  119  116  112  119  115  
1  112  119  116  112  119  115  
2  112  119  111  112  110  118  
3  112  119  111  101  110   97  
4  112  119  111  101  107   97  

[5 rows x 21 columns]


In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)
y_test=y_test.tolist()

y_train=y_train.tolist()
x_train=x_train.values.tolist()
x_test=x_test.values.tolist()




#### matrix in output is confusion matrix
## For different K's we print Confusion Matrix ----Accuracy----Recall---Precision----F1score

In [22]:
# Fitting K-NN to the Training set and # Predicting the Test set results

y_pred=knn_classifier(x_train,y_train,x_test,11)


# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))
print(recall_score(y_test,y_pred,pos_label='p'))
print(precision_score(y_test,y_pred,pos_label='p'))
print(f1_score(y_test,y_pred,pos_label='p'))


[[395   3]
 [  2 724]]
0.9955516014234875
0.9972451790633609
0.9958734525447043
0.9965588437715072


In [23]:

y_pred=knn_classifier(x_train,y_train,x_test,9)


# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))
print(recall_score(y_test,y_pred,pos_label='p'))
print(precision_score(y_test,y_pred,pos_label='p'))
print(f1_score(y_test,y_pred,pos_label='p'))


[[395   3]
 [  2 724]]
0.9955516014234875
0.9972451790633609
0.9958734525447043
0.9965588437715072


In [24]:

y_pred=knn_classifier(x_train,y_train,x_test,7)


# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))
print(recall_score(y_test,y_pred,pos_label='p'))
print(precision_score(y_test,y_pred,pos_label='p'))
print(f1_score(y_test,y_pred,pos_label='p'))


[[395   3]
 [  2 724]]
0.9955516014234875
0.9972451790633609
0.9958734525447043
0.9965588437715072


## we calculated same confusion matrix and accuracy with help of sklearn library 

In [34]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

neigh = KNeighborsClassifier(n_neighbors=7)
neigh.fit(x_train, y_train)
p = neigh.predict(x_test)
print (confusion_matrix(y_test,p))
print (accuracy_score(y_test,p))

[[395   3]
 [  2 724]]
0.9955516014234875


### Observation
    1. Changes in K value affects accuracy but percentage of affection is very less

### RESULT
    1. We get nearly same accuracy as sklearn library Knnclassifier for given value of k